version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/ticket_db?sslmode=disable
    depends_on:
      check-db-started:
        condition: service_completed_successfully
    networks:
      - ticket-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticket_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ticket_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ticket-network

  check-db-started:
    image: jwilder/dockerize:0.6.1
    depends_on:
      db:
        condition: service_healthy
    command: dockerize -wait tcp://db:5432 -timeout 30s
    networks:
      - ticket-network

volumes:
  postgres_data:

networks:
  ticket-network:
    driver: bridge
